#!/usr/bin/env ruby
# Github mirror for vim scripts
# http://vim-scripts.org/vim/scripts.html

git_bundles = [ 
  "git://github.com/vim-scripts/pathogen.vim.git",
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/tsaleh/vim-supertab.git",
  "git://github.com/digitaltoad/vim-jade.git",
  "git://github.com/Lokaltog/vim-easymotion.git",
  "git://github.com/vim-scripts/Javascript-Indentation.git",
  "git://github.com/vim-scripts/opencl.vim--Wierzowiecki.git",
  # "git://github.com/tsaleh/vim-tcomment.git",
  "git://github.com/vim-scripts/The-NERD-Commenter.git",
  "git://github.com/Shougo/neocomplcache.git",
  "git://github.com/hallettj/jslint.vim.git",
  "git://github.com/vim-scripts/pyflakes.vim.git",
  "git://github.com/vim-scripts/JavaScript-syntax.git",
  "git://github.com/vim-scripts/MatlabFilesEdition.git",
  "git://github.com/vim-scripts/Conque-Shell.git",
  "git://github.com/vim-scripts/L9.git",
  # "git://github.com/vim-scripts/Vim-R-plugin.git",
  "git://github.com/vim-scripts/FuzzyFinder.git",
  "git://github.com/vim-scripts/IndentAnything.git",
  # "git://github.com/vim-scripts/LaTeX-Suite-aka-Vim-LaTeX.git",
  # The repo below is newer for latexsuite
  "git://vim-latex.git.sourceforge.net/gitroot/vim-latex/vim-latex",
  # "git://github.com/davidfong/AutomaticLatexPlugin.git",
  "git://github.com/vim-scripts/JSON.vim.git",
  # "git://git.wincent.com/command-t.git",
  "git://github.com/vim-scripts/mlint.vim--Ibbotson.git"
]

hg_bundles = [
  # "https://bitbucket.org/kovisoft/slimv",
]

require 'fileutils'
require 'open-uri'

`git pull`

bundles_dir = File.expand_path(File.join(File.dirname(__FILE__), "bundle"))

FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

`git checkout README`

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

hg_bundles.each do |url|
  dir = url.split('/').last
  puts "  Unpacking #{url} into #{dir}"
  `hg clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".hg"))
  FileUtils.rm_rf(File.join(dir, ".hgtags"))
end

# working_dir = bundles_dir + "/command-t"
# FileUtils.cd(working_dir)
# `rake make`
